### ISSUE TITLE
Apollo website

### ISSUE THREAD

**Issue by cxd4** [Azimer/Apollo64#2]
As of this time, the [Apollo website](http://www.apollo64.com/indexn.htm) starting under indexn.htm seems to not work properly.

I can't remember the result and how it worked back in the late 2000s when I'd checked then.  I'm told it was working back then.  I was curious and felt like trying it now.  I in part assumed that if it's broken now it's no longer able to be maintained or somehow no longer under control or something.

If that was the case then I was going to say, the site could be maintained as a Git repository on GitHub.

**Comment by DerekTurtleRoe** [comment]
@Azimer Should we mirror the current site to see what is broken?

**Comment by Azimer** [comment]
If you're asking permission go ahead.  It's a static site with just enough PHP to do inline includes.  The whole site really needs a makeover.

**Comment by cxd4** [comment]
I'm not really a style designer personally.

I just do everything in static black and white with tables.

There is an infinite number of ways to make a graphically awesome design for the Apollo site.  I usually prefer limiting my possibilities to what's simple and traditional.  I usually design my sites for compatibility with text-mode browsers like Lynx, though not being able to use JavaScript kinda sucks.  I need JavaScript for WebGL; I do a lot of that as far as graphical sites.

**Comment by Azimer** [comment]
The site is located at https://azimer.github.io/apollo64.com/ .  I will add files as I can.  There will be a need to make changes as most of the links are static but shouldn't be.  The site should work on github and apollo64.com.
(This "gateway" page should also be removed)  I don't need a devlog or blog.  I am not an attention whore like I once was.

**Comment by cxd4** [comment]
The "gateway" page could in theory also be moved to http://azimer.github.io/ (which right now is a 404 because you haven't set up a site for your account, just the Apollo64.com subdirectory).

It could also be azimer.github.io/apollo instead of /apollo64.com by putting the website under a branch named `gh-pages` on this existing "Apollo64" repository right here, instead of having to create a new separate repository with .com added at the end of the name.  However the .com does help emphasize that this is a mirror/archive, not a new official location for the site.

**Comment by Azimer** [comment]
I functional mirror is now available at https://azimer.github.io/apollo64.com/ .  Further issues can be posted to https://github.com/Azimer/apollo64.com .

**Comment by cxd4** [comment]
...yeah.  It's all coming back to me now.  Now that the "Files" section and such actually works again, I do now remember the site working back in the late 2000s.

**Comment by DerekTurtleRoe** [comment]
@cxd4 Yeah, I thought I remembered correctly. The site was still functional after I announced the audit. 😄
